import { Inter } from 'next/font/google'
import Link from "next/link";
import all from '../app/css/all.css'
import style from './style.scss';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="container container_top" >
          <h1>Shopping</h1>
          <div className='serch'>
            <svg viewBox="0 0 512 512" fill="grey" className="header_searchIcon__M4CBh">
              <path d="M447.615 64.386C406.095 22.866 350.892 0 292.175 0s-113.92 22.866-155.439 64.386C95.217 105.905 72.35 161.108 72.35 219.824c0 53.683 19.124 104.421 54.132 144.458L4.399 486.366c-5.864 5.864-5.864 15.371 0 21.236C7.331 510.533 11.174 512 15.016 512s7.686-1.466 10.617-4.399l122.084-122.083c40.037 35.007 90.775 54.132 144.458 54.132 58.718 0 113.919-22.866 155.439-64.386 41.519-41.519 64.385-96.722 64.385-155.439s-22.865-113.92-64.384-155.439zm-21.236 289.643c-74.001 74-194.406 74-268.407 0-74-74-74-194.407 0-268.407 37.004-37.004 85.596-55.5 134.204-55.5 48.596 0 97.208 18.505 134.204 55.5 73.998 73.999 73.998 194.406-.001 268.407z"></path>
            </svg>
            <input type='text' id="text" name="text" required minLength="4" maxLength="20" placeholder="Search for products, brands and more... "/>
          </div>
          
          <Link href="/cart">
            <div className='cart'>
              <svg viewBox="0 0 512.002 512.002" className="header_cartIcon__286Ri">
                <path d="M194.59 382.711c-35.646 0-64.646 29-64.646 64.646s29 64.646 64.646 64.646 64.646-29 64.646-64.646-29.001-64.646-64.646-64.646zm0 90.504c-14.261 0-25.858-11.597-25.858-25.858 0-14.261 11.597-25.858 25.858-25.858 14.254 0 25.858 11.597 25.858 25.858 0 14.26-11.597 25.858-25.858 25.858zM385.941 382.711c-35.646 0-64.646 29-64.646 64.646s29 64.646 64.646 64.646 64.646-29 64.646-64.646-29-64.646-64.646-64.646zm0 90.504c-14.261 0-25.858-11.597-25.858-25.858 0-14.261 11.597-25.858 25.858-25.858 14.261 0 25.858 11.597 25.858 25.858 0 14.26-11.597 25.858-25.858 25.858zM498.088 126.274a19.4 19.4 0 00-15.179-7.324H143.326l-17.629-89.095a19.392 19.392 0 00-15.528-15.308L32.594.325C22.038-1.621 11.953 5.368 10.02 15.905s5.042 20.641 15.58 22.574l64.607 11.843 56.914 287.667c1.797 9.083 9.768 15.631 19.025 15.631h271.512c9.031 0 16.86-6.225 18.896-15.037l45.252-195.876a19.38 19.38 0 00-3.718-16.433zm-75.855 188.559H182.074l-31.075-157.089h307.519l-36.285 157.089z"></path>
              </svg>
              <h2>Cart</h2>
            </div>
          </Link>
          <div className="hamburger">
            <input type="checkbox" name="select" id="select"></input>
            <div className="select">
                <label htmlFor="select"><span>Hello <i className="fas fa-angle-down"></i></span></label>
                <div className="select__inner">
                    <div className="select__item">My Account</div>
                    <div className="select__item">My Order</div>
                    <div className="select__item">Favorites</div>
                    <div className="select__item">Logout</div>
                </div>
            </div>
            <input type="checkbox" name="select" id="menu__toggle"></input>
            <label className="menu__btn" htmlFor="menu__toggle">
              <span></span>
            </label>
            <div className="hamburger-menu">
              <div className="menu__box">
                <a className="menu__box_text" href="#">My Acount</a>
                <a className="menu__box_text" href="#">My Order</a>
                <a className="menu__box_text" href="#">Favorites</a>
                <a className="menu__box_text" href="#">Logout</a>
              </div>
            </div>
          </div>
        </div>
        <div className="container bottom_block">
          <div className='explore'>
            <h1>Explore</h1>
            <div className="container_links">
              <div className="link">
                <Link href="/" className='links'>New In</Link>
                <Link href="/clothing" className='links'>Clothing</Link>
                <Link href="/shoes" className='links'>Shoes</Link>
                <Link href="/phones" className='links'>Phones</Link>
                <Link href="/books" className='links'>Books</Link>
              </div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
